### ISSUE TITLE
Grafana Cloud integration

### ISSUE THREAD

**Issue by rootulp** [tedder/miner_exporter#13]
I've had some trouble getting this exporter to work with Grafana agent. Based on [this article](https://grafana.com/blog/2020/07/02/getting-started-with-the-grafana-agent-a-remote_write-focused-prometheus-agent/) it seems like Grafana Cloud supports default [integrations](https://grafana.com/docs/grafana-cloud/integrations/) that make it easier to set up the configuration for a Grafana agent. I'm not sure what the process is for on-boarding a new integration but I figured I'd create an issue if maintainers of this project were aware / interested in it.

**Comment by tedder** [comment]
Does it not work or do you need help setting it up?

**Comment by gradoj** [comment]
well first step would be testing it first before trying the setup the integration. i didn't test it but example 2 is very close to what you'd want to do to get it running with miner_exporter instead of blackbox_exporter. did it not scrape properly?

**Comment by rootulp** [comment]
> Does it not work or do you need help setting it up?

`miner_exporter` works for me. I'm able to verify that it's emitting metrics locally via:

```
[ec2-user@ip-172-31-52-73 ~]$ curl localhost:9825
# HELP python_gc_objects_collected_total Objects collected during gc
# TYPE python_gc_objects_collected_total counter
python_gc_objects_collected_total{generation="0"} 385.0
python_gc_objects_collected_total{generation="1"} 0.0
python_gc_objects_collected_total{generation="2"} 0.0
<...>
```

However, I'd rather not run a Prometheus instance on my EC2 instance. I'm attempting to use Grafana agent to send metrics to Grafana Cloud Prometheus. My most recent `grafana-agent.yml` doesn't appear to send miner_exporter metrics back :

```yml
server:
  log_level: info
  http_listen_port: 12345

prometheus:
  wal_directory: /tmp/wal
  configs:
    - name: helium-validator-exporter
      scrape_configs:
        - job_name: helium-validator-exporter
          static_configs:
            - targets: ['localhost:9825']
      remote_write:
        - url: https://prometheus-blocks-prod-us-central1.grafana.net/api/prom/push
          basic_auth:
            username: 123817
            password: <redacted>

integrations:
  agent:
    enabled: true
  node_exporter:
    enabled: true
  prometheus_remote_write:
  - url: https://prometheus-blocks-prod-us-central1.grafana.net/api/prom/push
    basic_auth:
      username: 123817
      password: <redacted>
```

**Comment by gradoj** [comment]
is you url correct in the yml config? Shouldn't it be:
https://prometheus-us-central1.grafana.net/api/prom/push

What do you see at http://localhost:12345/metrics ?

**Comment by rootulp** [comment]
> is you url correct in the yml config? Shouldn't it be:
> https://prometheus-us-central1.grafana.net/api/prom/push

On [Grafana cloud](https://grafana.com/orgs/rootulp/hosted-metrics/123817#sending-metrics) I see:

**Remote Write Endpoint:** 
https://prometheus-blocks-prod-us-central1.grafana.net/api/prom/push

And I've verified this is correct because agent and node_exporter metrics do end up in Grafana cloud. However, node_exporter metrics don't.

> What do you see at http://localhost:12345/metrics ?

I haven't been able to get the local server working so I don't see any metrics on the host.
```
[ec2-user@ip-172-31-52-73 ~]$ curl http://localhost:12345/metrics
curl: (7) Failed to connect to localhost port 12345: Connection refused
```

I appreciate your help on this! I'm working with Grafana support too.

**Comment by gradoj** [comment]
You using docker or binary for the grafana agent what is your command?

**Comment by rootulp** [comment]
> You using docker or binary for the grafana agent what is your command?

Docker

```
docker run \
    -v /tmp/wal:/etc/agent \
    -v /home/ec2-user/grafana-agent.yml:/etc/agent/agent.yaml \
    grafana/agent:v0.14.0
```

**Comment by gradoj** [comment]
I've never run grafana agent but most config files out there have a scrape interval
```
prometheus:
  wal_directory: /tmp/wal
  global:
    scrape_interval: 30s
```
Also looks like they've released a version 0.15

**Comment by rootulp** [comment]
👍 thanks! Just upgraded to 0.15 and added an explicit scrape_interval config. Still no luck

**Comment by rootulp** [comment]
Happy to close this issue given it's probably not the right forum to troubleshoot my issue with Grafana agent. Once again, really appreciate all your help @tedder @gradoj

**Comment by tedder** [comment]
@rootulp I'm going to reopen, please come back if you fix it. If someone gets time to dig in we can talk about it here. You're probably not the only one who is gonna want to do this 👍

**Comment by gradoj** [comment]
1.Create account at grafana.com. Get API Key, username and push url from My Account - Prometheus
2.Install agent on same machine as miner_exporter from https://github.com/grafana/agent/releases/
3.Create agent.yaml file from below. Replacing username and password with info from your GrafanaCloud
4.Run agent with `./agent-linux-amd64 -config.file agent.yaml`
5.verify metrics published locally with `curl  http://localhost:12345/metrics`
6.Create new dashboard in Grafana Cloud and see validator_ metrics are available from the prometheus datasource

tedders dashboard 14319 hosted by grafana doesn't work in grafana cloud for some reason but the exporter and agent are working. Need to create your own dashboard for now

```
server:
  log_level: info
  http_listen_port: 12345
prometheus:
  wal_directory: /tmp/wal
  global:
    scrape_interval: 30s
  configs:
    - name: agent
      host_filter: false
      scrape_configs:
        - job_name: 'miner_exporter'
          metrics_path: /probe
          params:
            module: [http_2xx]  # Look for a HTTP 200 response.
          static_configs:
            - targets:
              - grafana.com    # Target to probe with http.
          relabel_configs:
            - source_labels: [__address__]
              target_label: __param_target
            - source_labels: [__param_target]
              target_label: instance
            - target_label: __address__
              replacement: 127.0.0.1:9825  # The miner exporter's real hostname:port.
      remote_write:
        - url: https://prometheus-us-central1.grafana.net/api/prom/push
          basic_auth:
            username: 39xxxfromGrafanaCloud
            password: APIKeyfromGrafanaCloud
integrations:
  agent:
    enabled: true
  node_exporter:
    enabled: true

  prometheus_remote_write:
   - url: https://prometheus-us-central1.grafana.net/api/prom/push
     basic_auth:
       username: 39xxxfromGrafanaCloud
       password: APIKeyfromGrafanaCloud
```

**Comment by tedder** [comment]
As you've found in #21 this config has gotta be close. I think the instance names of the miner_exporter and node_exporter don't match and that's throwing it off.

**Comment by jathanism** [comment]
> As you've found in #21 this config has gotta be close. I think the instance names of the miner_exporter and node_exporter don't match and that's throwing it off.

I just confirmed locally that if you update `static_configs.targets` to match the hostname:port of the validator, the variable mapping works.

```
        static_configs:
          - targets:
            # - grafana.com    # Target to probe with http.
            - myvalidator:12345    # Target to probe with http.
```

~~I also had to adjust the regex for the variable definition for `server_name` to also capture the port number. (I'm currently unaware if this is also a result of my agent config)~~

Edit: I had saved a change to a copy I had made of the dashboard. I also have a few other bug fixes I've found in mapping the facts to the metrics. I'll be submitting a PR once I've got everything working.

**Comment by rootulp** [comment]
I'm re-attempting this setup given the tremendous progress on this thread!

1. I'm running testnet validator, watchtower, miner_exporter via @tedder 's [docker-compose gist](https://gist.github.com/tedder/e40460e92adbff07f6890806e12eb444) (thank you for this!)
2. I'm running grafana_agent via:
```bash
docker run -d --restart always \
--name grafana_agent \
--publish 12345:12345/tcp \
-v /tmp/wal:/etc/agent \
-v /home/ec2-user/grafana-agent.yml:/etc/agent/agent.yaml \
grafana/agent:v0.16.1
```
3. My grafana-agent.yml
```yaml
server:
  log_level: info
  http_listen_port: 12345
prometheus:
  wal_directory: /tmp/wal
  global:
    scrape_interval: 30s
  configs:
    - name: agent
      host_filter: false
      scrape_configs:
        - job_name: 'miner_exporter'
          metrics_path: /probe
          params:
            module: [http_2xx]  # Look for a HTTP 200 response.
          static_configs:
            - targets:
            # - grafana.com    # Target to probe with http.
              - myvalidator:12345
          relabel_configs:
            - source_labels: [__address__]
              target_label: __param_target
            - source_labels: [__param_target]
              target_label: instance
            - target_label: __address__
              replacement: 127.0.0.1:9825  # The miner exporter's real hostname:port.
      remote_write:
        - url: https://prometheus-blocks-prod-us-central1.grafana.net/api/prom/push
          basic_auth:
            username: <redacted>
            password: <redacted>
integrations:
  agent:
    enabled: true
  node_exporter:
    enabled: true

  prometheus_remote_write:
  - url: https://prometheus-blocks-prod-us-central1.grafana.net/api/prom/push
    basic_auth:
      username: <redacted>
      password: <redacted>
```
4. I have confirmed miner_exporter is working via
```
[ec2-user ~]$ curl localhost:9825
# HELP python_gc_objects_collected_total Objects collected during gc
# TYPE python_gc_objects_collected_total counter
python_gc_objects_collected_total{generation="0"} 372.0
python_gc_objects_collected_total{generation="1"} 0.0
python_gc_objects_collected_total{generation="2"} 0.0
...
```

5. I have reason to believe that grafana agent can't talk to miner_exporter

```
$ curl localhost:12345/metrics
...
net_conntrack_dialer_conn_failed_total{dialer_name="miner_exporter",reason="refused"} 174
net_conntrack_dialer_conn_failed_total{dialer_name="miner_exporter",reason="resolution"} 0
net_conntrack_dialer_conn_failed_total{dialer_name="miner_exporter",reason="timeout"} 0
net_conntrack_dialer_conn_failed_total{dialer_name="miner_exporter",reason="unknown"} 174
...
```

Therefore I currently suspect that I need to make some additional configuration change to allow the grafana agent docker container to talk to the miner_exporter docker container. In case this helps
```
[ec2-user@ip ~]$ n/agent --config…"   2 hours ago   Up 2 hours   0.0.0.0:12345->12345/tcp                           grafana_agent
> 158b7a4d91e0   ghcr.io/tedder/miner_exporter:latest             "/bin/sh -c /opt/app…"   6 hours ago   Up 6 hours   127.0.0.1:9825->9825/tcp                           miner_exporter
> 158d71424645   quay.io/team-helium/validator:latest-val-amd64   "/opt/miner/bin/mine…"   6 hours ago   Up 6 hours   0.0.0.0:2154->2154/tcp, 127.0.0.1:4467->4467/tcp   validator
> 997d72b9711d   containrrr/watchtower:latest                     "/watchtower validat…"   6 hours ago   Up 6 hours   8080/tcp                                           val_watchtower^C
[ec2-user@ip-172-31-52-73 ~]$ n/agent --config…"   2 hours ago   Up 2 hours   0.0.0.0:12345->12345/tcp                           grafana_agent
158b7a4d91e0   ghcr.io/tedder/miner_exporter:latest             "/bin/sh -c /opt/app…"   6 hours ago   Up 6 hours   127.0.0.1:9825->9825/tcp                           miner_exporter
158d71424645   quay.io/team-helium/validator:latest-val-amd64   "/opt/miner/bin/mine…"   6 hours ago   Up 6 hours   0.0.0.0:2154->2154/tcp, 127.0.0.1:4467->4467/tcp   validator
```

I'll read more on cross docker container communication and report back
